APP_NAME = "DFPrinter"
APP_TITLE = "Nidec DFPrinter"
DEFAULT_API_URL = "http://localhost:5000/print/"
CONFIG_FILENAME = "config.json"
USER_CONFIG_DIRNAME = ".dfprinter"
TEMPLATE_DIRNAME = "template"
DEFAULT_SCHEMA_FILENAME = "nidec_schema.json"
DEFAULT_TEMPLATE_FILENAME = "nidec_template.zpl"
